/*
 * complaitsWSO2Soap
 * Soap Complaints  API
 *
 * OpenAPI spec version: 2.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package org.wso2.client.api.complaitsWSO2Soap;

import org.wso2.client.api.ApiClient;
import org.wso2.client.api.ApiException;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import static org.junit.Assert.*;

/**
 * API tests for DefaultApi
 */


@Ignore
public class DefaultApiTest {

    //private Jaxb2Marshaller jaxb2Marshaller;

    DefaultApi defaultApi = new DefaultApi();

    ApiClient apiClient = defaultApi.getApiClient();


    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void postTest() throws ApiException {

        String soAPRequest = " <complaintLodgingRequest xmlns=\"http://www.anylytical.com/schema/ide/complaints\"><complaints><complaintsDetails><complaintReferences>DKDKD</complaintReferences><complaintDateTime>2019-05-01T00:00:00.000+02:00</complaintDateTime><dateFinalized>2019-05-14T00:00:00.000+02:00</dateFinalized><schemeReferences>SS</schemeReferences><insurer>Bryte</insurer></complaintsDetails><complaintsManagement><complaintDefinition>Insurance</complaintDefinition><complaintManagementFramework>FAIS</complaintManagementFramework></complaintsManagement><settlementPayment><complaintSettlementEstimate>1000</complaintSettlementEstimate><complaintGoodwillPayment>10000</complaintGoodwillPayment><compensationPayment>1000</compensationPayment></settlementPayment><policyHolderDetails><firstName>Lodwin</firstName><middleName>Mahlatse</middleName><surname>Moloto</surname><policyNumber>T56</policyNumber><contact><cellphone>0658619011</cellphone><telephone>0110110111</telephone><emailAddress>lodwin@anylytical.co.za</emailAddress></contact><address><PostalAddress><AddressLine1>22 sloane</AddressLine1><Suburb>Bryanston</Suburb><City>Joburg</City><Province>Gauteng</Province><PostalCode>2191</PostalCode></PostalAddress></address></policyHolderDetails><complaintPaymentType>Total</complaintPaymentType><complaintDecisionStatus>Rejected</complaintDecisionStatus><complaintEventLogStatus>Final</complaintEventLogStatus><complaintProcessStatus>Open</complaintProcessStatus><complaintItemQuestion>ComplaintItem001</complaintItemQuestion><complaintOccurrenceQuestion>ComplaintOccurrence002</complaintOccurrenceQuestion><complaintReason>PolicyPerformance</complaintReason><complaintTransactionAmount>Recovery</complaintTransactionAmount></complaints></complaintLodgingRequest>";
        String soAPAction = "";
        String header = "'SOAPAction': '\"http://www.w3.org/2003/05/soap-envelopee\"', 'Content-Type': 'application/soap+xml; charset=utf-8'";

        //Object Mapping

        apiClient.addDefaultHeader("Authorization", "Bearer 13b0e1b3-6240-3058-b031-4718031ab349");
        defaultApi.setApiClient(apiClient);

        defaultApi.postSoap12(soAPRequest);


    }

}
