/*
 * complaitsWSO2Soap
 * Soap Complaints  API
 *
 * OpenAPI spec version: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package org.wso2.client.api;

//@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2019-05-24T11:43:44.936+02:00")
public class Configuration {
    private static ApiClient defaultApiClient = new ApiClient();


    public static ApiClient getDefaultApiClient() {
        return defaultApiClient;
    }


    public static void setDefaultApiClient(ApiClient apiClient) {
        defaultApiClient = apiClient;
    }
}
