/*
 * complaitsWSO2Soap
 * Soap Complaints  API
 *
 * OpenAPI spec version: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package org.wso2.client.api.auth;

import org.wso2.client.api.Pair;

import java.util.Map;
import java.util.List;

// @javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2019-05-24T11:43:44.936+02:00")
public class OAuth implements Authentication {
  private String accessToken = "7c426850-2be9-39f8-98aa-605c8dd2ec32";

  public String getAccessToken() {
    return accessToken;
  }

  public void setAccessToken(String accessToken) {
    this.accessToken = accessToken;
  }

  @Override
  public void applyToParams(List<Pair> queryParams, Map<String, String> headerParams) {
    if (accessToken != null) {
      headerParams.put("Authorization", "Bearer " + accessToken);
    }
  }
}
